### ISSUE TITLE
System Admin & Membership Admin section not accessible

### ISSUE THREAD

**Issue by rafalinliyosar** [Chen-Huayi/Membership-Management#1]
System Admin & Membership Admin section not accessible, how do i make user id for them?

**Comment by chuaii** [comment]
Oh, system admin is set in built-in database (this database is created by own)：see file /server/config.js and there would be a systemAdmin in the exports.
And membership admin just created by system manager I think.

**Comment by rafalinliyosar** [comment]
> Oh, system admin is set in built-in database (this database is created by own)：see file /server/config.js and there would be a systemAdmin in the exports. And membership admin just created by system manager I think.

Thanks, found the password yesterday itself, we had made a local mongo db setup, so staff user was created in local db, so i searched the code with the phone number & found the sysAdmin password in the config file & was able to create the other users as well from within it, Anyway thanks a lot for reaching out, and good work on writing the code thanks
